name: Build Bottlerocket Kernel (Matrix)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk_version: [v0.61.0, v0.50.1]

    container:
      image: public.ecr.aws/bottlerocket/bottlerocket-sdk:${{ matrix.sdk_version }}
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build kernel
      run: |
        echo "Using Bottlerocket SDK version: ${{ matrix.sdk_version }}"
        git clone https://github.com/bottlerocket-os/bottlerocket /tmp/bottlerocket
        cd /tmp/bottlerocket
        ./tools/devtool setup