name: Build Bottlerocket Kernel with Patch
on:
  push:

jobs:
  build:
    name: Patch and Build Kernel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bottlerocket SDK in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: public.ecr.aws/bottlerocket/bottlerocket-sdk:v0.61.0
        options: -v ${{ github.workspace }}:/workspace
        run: |
          mkdir -p /tmp/build
          git clone https://github.com/bottlerocket-os/bottlerocket /tmp/build/bottlerocket
          cd /tmp/build/bottlerocket
          ./tools/devtool setup
