name: Build Kernel Module

on:
  workflow_dispatch:

concurrency:
  group: build-kernel-module
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Build
        run: echo "Building..."
